# Generated by Django 5.2.7 on 2025-10-25 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: GI-FI-N3', max_length=20, unique=True, verbose_name='Code')),
                ('specialite', models.CharField(choices=[('GI', 'Génie Informatique et Télécommunication'), ('GLO', 'Génie Logistique'), ('GRT', 'Génie des Réseaux et Télécommunications'), ('CSCD', 'Cyber-Sécurité et Cryptographie Digitale'), ('SSI', 'Systèmes et Sécurité Informatique')], max_length=10, verbose_name='Spécialité')),
                ('formation', models.CharField(choices=[('FI', 'Formation Initiale'), ('FA', 'Formation en Alternance'), ('MP', 'Master Professionnel')], max_length=2, verbose_name='Type de formation')),
                ('niveau', models.CharField(choices=[('N1', 'Niveau 1'), ('N2', 'Niveau 2'), ('N3', 'Niveau 3'), ('N4', 'Niveau 4'), ('N5', 'Niveau 5')], max_length=2, verbose_name='Niveau')),
                ('jour_semaine', models.CharField(blank=True, choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=10, null=True, verbose_name='Jour principal')),
                ('heure_debut', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('salle_principale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filieres_principales', to='courses.salle', verbose_name='Salle principale')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'ordering': ['specialite', 'formation', 'niveau'],
                'unique_together': {('specialite', 'formation', 'niveau')},
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='etudiants/photos/', verbose_name='Photo')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='students.filiere', verbose_name='Filière')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='HoraireSupplementaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=10, verbose_name='Jour')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('remarque', models.CharField(blank=True, max_length=200, null=True, verbose_name='Remarque')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires_supplementaires', to='students.filiere', verbose_name='Filière')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horaires_supplementaires', to='courses.salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Horaire supplémentaire',
                'verbose_name_plural': 'Horaires supplémentaires',
                'ordering': ['filiere', 'jour_semaine', 'heure_debut'],
            },
        ),
    ]
