# Generated by Django 5.2.7 on 2025-10-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_horairesupplementaire_jour_semaine'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='matricule_departement',
            field=models.CharField(blank=True, help_text='Matricule généré automatiquement (ex: 25GITGRT300001)', max_length=20, null=True, unique=True, verbose_name='Matricule Département'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(help_text="Matricule personnel de l'étudiant", max_length=20, unique=True, verbose_name='Matricule'),
        ),
    ]
