# Generated by Django 5.2.7 on 2025-10-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_etudiant_matricule_departement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='niveau',
            field=models.CharField(choices=[('N3', 'Niveau 3'), ('N4', 'Niveau 4'), ('N5', 'Niveau 5')], max_length=2, verbose_name='Niveau'),
        ),
    ]
