# Generated by Django 5.2.7 on 2025-10-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_filiere_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='niveau',
            field=models.CharField(choices=[('N1', 'Niveau 1'), ('N2', 'Niveau 2'), ('N3', 'Niveau 3'), ('N4', 'Niveau 4'), ('N5', 'Niveau 5')], max_length=2, verbose_name='Niveau'),
        ),
    ]
