# Generated by Django 5.2.7 on 2025-10-19 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('specialite', models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité')),
                ('grade', models.CharField(blank=True, choices=[('ASSISTANT', 'Assistant'), ('CHARGE', 'Chargé de cours'), ('MAITRE_ASSISTANT', 'Maître Assistant'), ('MAITRE_CONFERENCE', 'Maître de Conférences'), ('PROFESSEUR', 'Professeur')], max_length=20, null=True, verbose_name='Grade')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True)),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='enseignants/photos/', verbose_name='Photo')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
