# Generated by Django 5.2.7 on 2025-10-19 06:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('type_salle', models.CharField(choices=[('AMPHI', 'Amphithéâtre'), ('TD', 'Salle de TD'), ('TP', 'Salle de TP'), ('LAB', 'Laboratoire')], max_length=10, verbose_name='Type de salle')),
                ('capacite', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité')),
                ('batiment', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bâtiment')),
                ('etage', models.IntegerField(blank=True, null=True, verbose_name='Étage')),
                ('equipements', models.TextField(blank=True, help_text='Projecteur, Tableau, Ordinateurs, etc.', null=True, verbose_name='Équipements')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['batiment', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('semestre', models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')], verbose_name='Semestre')),
                ('annee_academique', models.CharField(help_text='Ex: 2024-2025', max_length=9, verbose_name='Année académique')),
                ('jour_semaine', models.CharField(blank=True, choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=10, null=True, verbose_name='Jour de la semaine')),
                ('heure_debut', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('credits', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Crédits')),
                ('coefficient', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='Coefficient')),
                ('volume_horaire_cm', models.IntegerField(default=0, verbose_name='Volume horaire CM (heures)')),
                ('volume_horaire_td', models.IntegerField(default=0, verbose_name='Volume horaire TD (heures)')),
                ('volume_horaire_tp', models.IntegerField(default=0, verbose_name='Volume horaire TP (heures)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='teachers.enseignant', verbose_name='Enseignant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='students.filiere', verbose_name='Filière')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='students.niveau', verbose_name='Niveau')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='courses.salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['filiere', 'niveau', 'code'],
                'unique_together': {('code', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='SeanceCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('type_seance', models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques'), ('EXAM', 'Examen'), ('CONTROLE', 'Contrôle Continu')], default='CM', max_length=20, verbose_name='Type de séance')),
                ('contenu', models.TextField(blank=True, help_text='Résumé du contenu de la séance', null=True, verbose_name='Contenu')),
                ('presente', models.BooleanField(default=False, help_text='La présence a-t-elle été faite?', verbose_name='Présence effectuée')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='courses.cours', verbose_name='Cours')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Séance de cours',
                'verbose_name_plural': 'Séances de cours',
                'ordering': ['-date', '-heure_debut'],
                'unique_together': {('cours', 'date', 'heure_debut')},
            },
        ),
    ]
