# Generated by Django 5.2.7 on 2025-10-25 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='students.filiere', verbose_name='Filière'),
        ),
        migrations.AddField(
            model_name='cours',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='courses.salle', verbose_name='Salle'),
        ),
        migrations.AddField(
            model_name='seancecours',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances', to='courses.cours', verbose_name='Cours'),
        ),
        migrations.AddField(
            model_name='seancecours',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.salle', verbose_name='Salle'),
        ),
        migrations.AlterUniqueTogether(
            name='cours',
            unique_together={('code', 'annee_academique')},
        ),
        migrations.AlterUniqueTogether(
            name='seancecours',
            unique_together={('cours', 'date', 'heure_debut')},
        ),
    ]
