# Generated by Django 5.2.7 on 2025-10-26 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='heure_debut',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='heure_fin',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='jour_semaine',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='salle',
        ),
        migrations.AddField(
            model_name='seancecours',
            name='est_exceptionnelle',
            field=models.BooleanField(default=False, help_text='Séance hors planning habituel', verbose_name='Séance exceptionnelle'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='teachers.enseignant', verbose_name='Enseignant'),
        ),
        migrations.CreateModel(
            name='HorairesCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=10, verbose_name='Jour de la semaine')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('type_seance', models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques')], default='CM', max_length=20, verbose_name='Type de séance')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('remarque', models.TextField(blank=True, null=True, verbose_name='Remarque')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='courses.cours', verbose_name='Cours')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horaires_cours', to='courses.salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Horaire de cours',
                'verbose_name_plural': 'Horaires de cours',
                'ordering': ['cours', 'jour_semaine', 'heure_debut'],
                'unique_together': {('cours', 'jour_semaine', 'heure_debut')},
            },
        ),
        migrations.AddField(
            model_name='seancecours',
            name='horaire_planifie',
            field=models.ForeignKey(blank=True, help_text='Laisser vide si séance exceptionnelle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_effectuees', to='courses.horairescours', verbose_name='Horaire planifié'),
        ),
    ]
