# Generated by Django 5.2.7 on 2025-10-26 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_seancecours_horaire_planifie_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='heure_debut',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='heure_fin',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='jour_semaine',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='salle',
        ),
        migrations.AddField(
            model_name='seancecours',
            name='est_hors_planning',
            field=models.BooleanField(default=False, help_text='Séance ajoutée manuellement (rattrapage, etc.)', verbose_name='Hors planning'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='teachers.enseignant', verbose_name='Enseignant'),
        ),
        migrations.AlterField(
            model_name='seancecours',
            name='type_seance',
            field=models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques'), ('EXAM', 'Examen'), ('CONTROLE', 'Contrôle Continu'), ('RATTRAPAGE', 'Rattrapage')], default='CM', max_length=20, verbose_name='Type de séance'),
        ),
        migrations.CreateModel(
            name='HoraireCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi'), ('DIMANCHE', 'Dimanche')], max_length=10, verbose_name='Jour de la semaine')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('type_seance', models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques')], default='CM', max_length=10, verbose_name='Type de séance')),
                ('ordre', models.IntegerField(default=1, help_text="Ordre d'affichage", verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='courses.cours', verbose_name='Cours')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Horaire de cours',
                'verbose_name_plural': 'Horaires de cours',
                'ordering': ['cours', 'ordre', 'jour_semaine', 'heure_debut'],
                'unique_together': {('cours', 'jour_semaine', 'heure_debut')},
            },
        ),
        migrations.AddField(
            model_name='seancecours',
            name='horaire_cours',
            field=models.ForeignKey(blank=True, help_text="Si null, c'est une séance hors planning", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances_generees', to='courses.horairecours', verbose_name='Horaire de référence'),
        ),
    ]
