# Generated by Django 5.2.7 on 2025-10-26 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_cours_heure_debut_remove_cours_heure_fin_and_more'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seancecours',
            name='horaire_cours',
        ),
        migrations.RemoveField(
            model_name='seancecours',
            name='est_hors_planning',
        ),
        migrations.AddField(
            model_name='cours',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de début'),
        ),
        migrations.AddField(
            model_name='cours',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de fin'),
        ),
        migrations.AddField(
            model_name='cours',
            name='jour_semaine',
            field=models.CharField(blank=True, choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=10, null=True, verbose_name='Jour de la semaine'),
        ),
        migrations.AddField(
            model_name='cours',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='courses.salle', verbose_name='Salle'),
        ),
        migrations.AlterField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='teachers.enseignant', verbose_name='Enseignant'),
        ),
        migrations.AlterField(
            model_name='seancecours',
            name='type_seance',
            field=models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques'), ('EXAM', 'Examen'), ('CONTROLE', 'Contrôle Continu')], default='CM', max_length=20, verbose_name='Type de séance'),
        ),
        migrations.DeleteModel(
            name='HoraireCours',
        ),
    ]
