# Generated by Django 5.2.7 on 2025-10-27 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_seancecours_horaire_cours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='heure_debut',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='heure_fin',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='jour_semaine',
        ),
        migrations.AddField(
            model_name='salle',
            name='remarque',
            field=models.TextField(blank=True, null=True, verbose_name='Remarque'),
        ),
        migrations.AddField(
            model_name='seancecours',
            name='annulee',
            field=models.BooleanField(default=False, verbose_name='Annulée'),
        ),
        migrations.AddField(
            model_name='seancecours',
            name='motif_annulation',
            field=models.TextField(blank=True, null=True, verbose_name="Motif d'annulation"),
        ),
        migrations.AddField(
            model_name='seancecours',
            name='remarque',
            field=models.TextField(blank=True, null=True, verbose_name='Remarque'),
        ),
        migrations.AlterField(
            model_name='salle',
            name='type_salle',
            field=models.CharField(choices=[('AMPHI', 'Amphithéâtre'), ('TD', 'Salle de TD'), ('TP', 'Salle de TP'), ('LAB', 'Laboratoire')], default='CM', max_length=10, verbose_name='Type de salle'),
        ),
        migrations.CreateModel(
            name='HoraireCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi'), ('DIMANCHE', 'Dimanche')], max_length=10, verbose_name='Jour de la semaine')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('type_seance', models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques'), ('EXAM', 'Examen'), ('CONTROLE', 'Contrôle Continu')], default='CM', max_length=10, verbose_name='Type de séance')),
                ('remarque', models.TextField(blank=True, null=True, verbose_name='Remarque')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='courses.cours', verbose_name='Cours')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horaires_cours', to='courses.salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Horaire de cours',
                'verbose_name_plural': 'Horaires de cours',
                'ordering': ['cours', 'jour_semaine', 'heure_debut'],
                'unique_together': {('cours', 'jour_semaine', 'heure_debut')},
            },
        ),
        migrations.AddField(
            model_name='seancecours',
            name='horaire_cours',
            field=models.ForeignKey(blank=True, help_text='Horaire régulier dont cette séance est issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seances', to='courses.horairecours', verbose_name='Horaire de référence'),
        ),
    ]
