# Generated by Django 5.2.7 on 2025-10-19 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiqueCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=200, unique=True, verbose_name='Clé')),
                ('valeur', models.JSONField(verbose_name='Valeur')),
                ('date_calcul', models.DateTimeField(auto_now=True, verbose_name='Date de calcul')),
                ('date_expiration', models.DateTimeField(verbose_name="Date d'expiration")),
            ],
            options={
                'verbose_name': 'Statistique en cache',
                'verbose_name_plural': 'Statistiques en cache',
                'ordering': ['-date_calcul'],
            },
        ),
        migrations.CreateModel(
            name='RapportPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('type_rapport', models.CharField(choices=[('ETUDIANT', 'Par étudiant'), ('COURS', 'Par cours'), ('FILIERE', 'Par filière'), ('NIVEAU', 'Par niveau'), ('GLOBAL', 'Global')], max_length=20, verbose_name='Type de rapport')),
                ('format_fichier', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], default='PDF', max_length=10, verbose_name='Format')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='rapports/', verbose_name='Fichier')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('nombre_pages', models.IntegerField(default=1, verbose_name='Nombre de pages')),
                ('taille_fichier', models.IntegerField(default=0, help_text='Taille en octets', verbose_name='Taille du fichier')),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.cours', verbose_name='Cours')),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.etudiant', verbose_name='Étudiant')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.filiere', verbose_name='Filière')),
                ('genere_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.niveau', verbose_name='Niveau')),
            ],
            options={
                'verbose_name': 'Rapport de présence',
                'verbose_name_plural': 'Rapports de présence',
                'ordering': ['-date_generation'],
            },
        ),
    ]
