# Generated by Django 5.2.7 on 2025-10-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Justificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_justificatif', models.CharField(choices=[('MEDICAL', 'Certificat médical'), ('FAMILLE', 'Raison familiale'), ('ADMIN', 'Raison administrative'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de justificatif')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('fichier', models.FileField(upload_to='justificatifs/', verbose_name='Fichier')),
                ('valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('remarque_validation', models.TextField(blank=True, null=True, verbose_name='Remarque de validation')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
            ],
            options={
                'verbose_name': 'Justificatif',
                'verbose_name_plural': 'Justificatifs',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('P', 'Présent'), ('A', 'Absent'), ('R', 'Retard'), ('J', 'Justifié')], default='A', max_length=1, verbose_name='Statut')),
                ('remarque', models.TextField(blank=True, null=True, verbose_name='Remarque')),
                ('justification', models.FileField(blank=True, null=True, upload_to='justificatifs/', verbose_name='Justificatif')),
                ('heure_arrivee', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-seance__date', 'etudiant__nom'],
            },
        ),
    ]
