# Generated by Django 5.2.7 on 2025-10-19 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_justificatif', models.CharField(choices=[('MEDICAL', 'Certificat médical'), ('FAMILLE', 'Raison familiale'), ('ADMIN', 'Raison administrative'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de justificatif')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('fichier', models.FileField(upload_to='justificatifs/', verbose_name='Fichier')),
                ('valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('remarque_validation', models.TextField(blank=True, null=True, verbose_name='Remarque de validation')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs', to='students.etudiant', verbose_name='Étudiant')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificatifs_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Justificatif',
                'verbose_name_plural': 'Justificatifs',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('P', 'Présent'), ('A', 'Absent'), ('R', 'Retard'), ('J', 'Justifié')], default='A', max_length=1, verbose_name='Statut')),
                ('remarque', models.TextField(blank=True, null=True, verbose_name='Remarque')),
                ('justification', models.FileField(blank=True, null=True, upload_to='justificatifs/', verbose_name='Justificatif')),
                ('heure_arrivee', models.TimeField(blank=True, null=True, verbose_name="Heure d'arrivée")),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='students.etudiant', verbose_name='Étudiant')),
                ('saisi_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Saisi par')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='courses.seancecours', verbose_name='Séance')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-seance__date', 'etudiant__nom'],
                'unique_together': {('etudiant', 'seance')},
            },
        ),
    ]
