# Generated by Django 5.2.7 on 2025-10-25 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('courses', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='justificatif',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs', to='students.etudiant', verbose_name='Étudiant'),
        ),
        migrations.AddField(
            model_name='justificatif',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificatifs_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddField(
            model_name='presence',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='students.etudiant', verbose_name='Étudiant'),
        ),
        migrations.AddField(
            model_name='presence',
            name='saisi_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Saisi par'),
        ),
        migrations.AddField(
            model_name='presence',
            name='seance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='courses.seancecours', verbose_name='Séance'),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('etudiant', 'seance')},
        ),
    ]
