# Generated by Django 5.2.7 on 2025-10-28 13:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='justificatif',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='justificatif',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='justificatif',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Document justificatif'),
        ),
        migrations.AlterField(
            model_name='justificatif',
            name='motif',
            field=models.TextField(verbose_name="Motif de l'absence"),
        ),
        migrations.AlterField(
            model_name='justificatif',
            name='type_justificatif',
            field=models.CharField(choices=[('MEDICAL', 'Certificat Médical'), ('FAMILLE', 'Raison Familiale'), ('ADMIN', 'Démarche Administrative'), ('STAGE', 'Stage/Formation'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de justificatif'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='justification',
            field=models.FileField(blank=True, null=True, upload_to='presences/justificatifs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Fichier justificatif'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='saisi_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Saisi par'),
        ),
    ]
