# Generated by Django 5.2.7 on 2025-10-28 14:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_justificatif_date_modification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='justificatif_formel',
            field=models.ForeignKey(blank=True, help_text="Justificatif validé par l'administration", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_couvertes', to='attendance.justificatif', verbose_name='Justificatif formel'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='justification',
            field=models.FileField(blank=True, help_text='Pour justification immédiate lors de la séance', null=True, upload_to='presences/justificatifs/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Justificatif rapide'),
        ),
    ]
